// add delayed functionality here
window.adobeDataLayer = window.adobeDataLayer || []
console.log('Meta description content:');

// Code Generated by Sidekick is for learning and experimentation purposes only.
const metaDescription = document.querySelector('meta[name="description"]');

if (metaDescription) {
  console.log('Meta description content:', metaDescription.getAttribute('content'));
} else {
  console.error('Meta description element not found');
}

adobeDataLayer.push({
    "event": "page_view",
    "pageInfo": {
        "pageName": metaDescription,
        "pageURL": "<Page URL Excluding Query Parameters>",
        "siteSection": "<L1 of site hierarchy>",
        "siteSubSection1": "<L2 of site hierarchy>",
        "siteSubSection2": "<L3 of site hierarchy>",
        "previousPageName": "<Previous Page Name>",
        "environment": "<Environment of the website>",
        "businessCountryLanguage": "<Business Country and Language>"

    }
})