// Code Generated by Sidekick is for learning and experimentation purposes only.
const scriptElement = document.createElement('script');

// Set the src attribute
scriptElement.src = "https://assets.adobedtm.com/d8c48e012a5d/d1d9cb2d2584/launch-72ce3ebd3334-development.min.js";

// Set the async attribute
scriptElement.async = true;

// Append the script element to the document's head or body
document.head.appendChild(scriptElement);

// Log to confirm the script has been added
console.log('Script element added:', scriptElement);


window.adobeDataLayer = window.adobeDataLayer || [];
const metaDescription = document.querySelector('meta[name="description"]').getAttribute('content');
const pageUrl = document.querySelector('meta[name="canonical"]').getAttribute('content');
const htmlLang = document.documentElement.getAttribute('lang');
adobeDataLayer.push({
  'event': 'page_view',
  'pageInfo': {
    'pageName': metaDescription,
    'pageURL': pageUrl,
    'businessCountryLanguage': htmlLang
  }
});